#!/bin/bash
# Name: GmnFrost
# Author: obliviousgmn
# Link: http://dotshare.it/dots/547/

background="#1C1C23"
foreground="#9BBBC6"
cursorColor=$foreground

# Black
color0="#323246"
color8=$color0

# Red
color1="#5A7882"
color9=$color1

# Green
color2="#8C8CA0"
color10=$color2

# Yellow
color3="#1E828C"
color11=$color3

# Blue
color4="#3C788C"
color12=$color4

# Magenta
color5="#6EA0B4"
color13=$color5

# Cyan
color6="#6E8CA0"
color14=$color6

# White
color7="#96BEC8"
color15=$color7